"""Fine-tune the GNN on manually ID-labelled real detector outputs.

Annotation JSONL format:
{"frame_name":"...", "detections":[{"xy":[x,y],"lamp_id":"F0", "color":"green"}, ...]}
Use lamp_id null for an outlier/reflection.  At least 150 diverse frames with
both layers visible are recommended; retain the synthetic pre-training first.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import yaml
from tqdm import trange

if __package__ in (None, ""):
    # Support `python src/train_gnn_real.py` as well as the preferred module
    # invocation `python -m src.train_gnn_real`.
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from src.config import load_array_configuration
    from src.graph import GuidingLightGNN, knn_edges, log_optimal_transport, observation_features, template_features
    from src.schema import COLOR_INDEX, LightDetection
    from src.train_gnn_synthetic import transport_loss
else:
    from .config import load_array_configuration
    from .graph import GuidingLightGNN, knn_edges, log_optimal_transport, observation_features, template_features
    from .schema import COLOR_INDEX, LightDetection
    from .train_gnn_synthetic import transport_loss


def load_examples(path: Path, configuration, reviewed_only: bool = True) -> list[tuple[list[LightDetection], np.ndarray]]:
    id_to_index = {lamp.lamp_id: index for index, lamp in enumerate(configuration.lights)}
    examples: list[tuple[list[LightDetection], np.ndarray]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        record = json.loads(line)
        # JSONL generated by the visual annotator uses an explicit review state.
        # Legacy annotations without the field remain supported.
        if reviewed_only and record.get("review_status") not in (None, "reviewed"):
            continue
        detections: list[LightDetection] = []
        labels: list[int] = []
        for entry in record.get("detections", []):
            lamp_id = entry.get("lamp_id")
            if lamp_id is not None and lamp_id not in id_to_index:
                raise ValueError(f"Unknown lamp_id {lamp_id!r} at {path}:{line_number}")
            color = str(entry.get("color", "other"))
            probs = np.asarray(entry.get("color_probs", [0.05, 0.05, 0.90]), dtype=np.float32)
            if probs.shape != (3,):
                probs = np.full(3, 0.05, dtype=np.float32)
                probs[COLOR_INDEX.get(color, COLOR_INDEX["other"])] = 0.90
            probs = np.clip(probs, 0.001, None)
            probs /= probs.sum()
            detections.append(
                LightDetection(
                    np.asarray(entry["xy"], dtype=np.float64),
                    float(entry.get("confidence", 0.95)),
                    probs,
                    color,
                    float(entry.get("radius", 7.0)),
                    float(entry.get("brightness", 220.0)),
                    "real_annotation",
                    float(entry.get("center_quality", 0.95)),
                )
            )
            labels.append(id_to_index[lamp_id] if lamp_id is not None else -1)
        if len(detections) >= 4:
            examples.append((detections, np.asarray(labels, dtype=np.int64)))
    if not examples:
        raise ValueError("No usable annotated frames found.")
    return examples


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--annotations", required=True)
    parser.add_argument("--array-config", default="configs/lamp_array_3d.yaml")
    parser.add_argument("--gnn-config", default="configs/gnn_matcher.yaml")
    parser.add_argument("--init", default="models/gnn_matcher_synthetic.pt")
    parser.add_argument("--output", default="models/gnn_matcher_real.pt")
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configuration = load_array_configuration(args.array_config)
    with Path(args.gnn_config).open("r", encoding="utf-8") as handle:
        settings = yaml.safe_load(handle)
    examples = load_examples(Path(args.annotations), configuration)
    model = GuidingLightGNN(**settings["model"]).to(args.device)
    init_path = Path(args.init)
    if init_path.exists():
        checkpoint = torch.load(init_path, map_location=args.device)
        model.load_state_dict(checkpoint["state_dict"])
    optimizer = torch.optim.AdamW(model.parameters(), lr=float(settings["training"]["learning_rate"]) * 0.25, weight_decay=float(settings["training"]["weight_decay"]))
    rng = np.random.default_rng(args.seed)
    template = torch.from_numpy(template_features(configuration)).to(args.device)
    template_points = np.asarray([lamp.xyz[:2] for lamp in configuration.lights], dtype=np.float32)
    template_edges_np, template_attrs_np = knn_edges(template_points, configuration.k_neighbors)
    template_edges = torch.from_numpy(template_edges_np).to(args.device)
    template_attrs = torch.from_numpy(template_attrs_np).to(args.device)
    for epoch in trange(args.epochs, desc="Real GNN epochs"):
        model.train()
        losses = []
        for example_index in rng.permutation(len(examples)):
            detections, labels = examples[int(example_index)]
            # Small coordinate jitter prevents overfitting to manually clicked pixels.
            augmented = [
                LightDetection(item.xy + rng.normal(0.0, 0.7, 2), item.confidence, item.color_probs, item.color, item.radius, item.brightness, item.source, item.center_quality)
                for item in detections
            ]
            points = np.asarray([item.xy for item in augmented], dtype=np.float32)
            edges_np, attributes_np = knn_edges(points, configuration.k_neighbors)
            logits = model(
                torch.from_numpy(observation_features(augmented)).to(args.device),
                torch.from_numpy(edges_np).to(args.device),
                torch.from_numpy(attributes_np).to(args.device),
                template,
                template_edges,
                template_attrs,
            )
            transport = log_optimal_transport(logits, model.bin_score, int(settings["training"].get("sinkhorn_iterations", 60)))
            loss = transport_loss(transport, labels, len(configuration.lights))
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            losses.append(float(loss.detach().cpu()))
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"epoch={epoch + 1} loss={np.mean(losses):.4f}")
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    torch.save({"state_dict": model.state_dict(), "model": settings["model"], "array_config": args.array_config, "training": "real_id_finetune_ot"}, output)
    print(f"Saved real-data GNN checkpoint: {output}")


if __name__ == "__main__":
    main()
